# Generated by Django 4.0.3 on 2022-03-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_coder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automoviles',
            old_name='id',
            new_name='chasis',
        ),
        migrations.RenameField(
            model_name='motocicletas',
            old_name='id',
            new_name='chasis',
        ),
    ]
